spring:
  security:
    oauth2:
      client:
        registration:
          yandex:
            clientId: <client-id>
            clientSecret: <secret-id>
            authorization-grant-type: authorization_code
            redirectUri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize?
            token-uri: https://oauth.yandex.ru/token
            user-info-uri: https://login.yandex.ru/info?
            user-name-attribute: login
logging:
  level:
    org:
      springframework:
        web: INFO
app:
  get:
    resources:
      limit: 32
